services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: loudrr
      POSTGRES_PASSWORD: loudrr
      POSTGRES_DB: loudrr
    ports:
      - "5432:5432"
    volumes:
      - loudrr_db:/var/lib/postgresql/data

volumes:
  loudrr_db:

