# Generated by Django 5.2.8 on 2026-01-12 15:28

import django.db.models.deletion
import django.utils.timezone
import miniapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        db_index=True,
                        default=miniapp.models.generate_session_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("failed", "Failed Verification"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("posts_shown", models.IntegerField(default=0)),
                ("clicks_recorded", models.IntegerField(default=0)),
                ("credits_awarded", models.IntegerField(default=0)),
                ("verification_passed", models.BooleanField(blank=True, null=True)),
                ("verification_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engagement_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("click_verified", models.BooleanField(default=False)),
                ("api_verified", models.BooleanField(blank=True, null=True)),
                ("api_verification_data", models.JSONField(blank=True, default=dict)),
                ("credit_granted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_clicks",
                        to="posts.post",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="miniapp.engagementsession",
                    ),
                ),
            ],
            options={
                "db_table": "session_clicks",
            },
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(
                fields=["user", "-created_at"], name="engagement__user_id_c30967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(
                fields=["session_token"], name="engagement__session_d4de91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(fields=["status"], name="engagement__status_d2bcf6_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionclick",
            index=models.Index(
                fields=["session", "-clicked_at"], name="session_cli_session_4bed60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionclick",
            constraint=models.UniqueConstraint(
                fields=("session", "post"), name="unique_session_post_click"
            ),
        ),
    ]
