# Generated by Django 5.2.8 on 2026-01-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionclick",
            name="engagement_intent",
            field=models.CharField(
                choices=[
                    ("like", "Like Only"),
                    ("reply", "Reply Only"),
                    ("both", "Like + Reply"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionclick",
            name="like_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionclick",
            name="reply_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionclick",
            name="used_ai_assist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionclick",
            name="used_quick_like",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionclick",
            name="used_quick_reply",
            field=models.BooleanField(default=False),
        ),
    ]
