# Generated by Django 5.2.8 on 2026-01-23 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoudProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name, e.g. 'Uniswap V4 Launch'",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "description",
                    models.TextField(help_text="Description shown to users"),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Project logo URL", null=True
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(help_text="When the project becomes visible"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        help_text="When the project stops accepting submissions"
                    ),
                ),
                (
                    "min_tweetscout_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum TweetScout score required to submit (0 = no minimum)",
                    ),
                ),
                (
                    "max_submissions_per_user",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Maximum submissions per user for this project",
                    ),
                ),
                (
                    "reward_pool",
                    models.CharField(
                        blank=True,
                        help_text="Display text for reward pool, e.g. '$5000 USDC'",
                        max_length=100,
                    ),
                ),
                (
                    "reward_description",
                    models.TextField(blank=True, help_text="Additional reward details"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Admin can pause/unpause the project"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "loud_projects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "ends_at"],
                        name="loud_projec_is_acti_756f3f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoudLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("submission_count", models.PositiveIntegerField(default=0)),
                ("last_submission_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loud_leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="loud.loudproject",
                    ),
                ),
            ],
            options={
                "db_table": "loud_leaderboard",
                "indexes": [
                    models.Index(
                        fields=["project", "-total_points"],
                        name="loud_leader_project_0a90e8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "user"),
                        name="unique_project_user_leaderboard",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoudSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x_link", models.URLField(help_text="Normalized X/Twitter link")),
                (
                    "tweet_id",
                    models.CharField(
                        db_index=True,
                        help_text="Extracted tweet ID for global uniqueness",
                        max_length=50,
                    ),
                ),
                (
                    "x_username",
                    models.CharField(
                        help_text="Username extracted from link", max_length=50
                    ),
                ),
                (
                    "points_awarded",
                    models.PositiveIntegerField(
                        help_text="Points calculated from TweetScout score at submission"
                    ),
                ),
                (
                    "tweetscout_score_at_submission",
                    models.FloatField(
                        help_text="Snapshot of user's TweetScout score for audit"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="loud.loudproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loud_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loud_submissions",
                "indexes": [
                    models.Index(
                        fields=["user", "submitted_at"],
                        name="loud_submis_user_id_16949c_idx",
                    ),
                    models.Index(
                        fields=["project", "-points_awarded"],
                        name="loud_submis_project_f5893b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tweet_id",), name="unique_submission_tweet_id"
                    )
                ],
            },
        ),
    ]
