# Generated by Django 5.2.8 on 2026-01-25 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loud", "0004_add_user_project_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoudPointAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("deduction", "Point Deduction"),
                            ("addition", "Point Addition"),
                            ("void", "Submission Voided"),
                        ],
                        default="deduction",
                        max_length=20,
                    ),
                ),
                (
                    "points_change",
                    models.IntegerField(
                        help_text="Negative for deductions, positive for additions"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Required reason for audit trail"),
                ),
                ("points_before", models.PositiveIntegerField()),
                ("points_after", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loud_point_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leaderboard_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="loud.loudleaderboardentry",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="If voiding a specific submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="loud.loudsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "loud_point_adjustments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["leaderboard_entry", "-created_at"],
                        name="loud_point__leaderb_4f70cd_idx",
                    )
                ],
            },
        ),
    ]
