# Generated by Django 5.2.8 on 2026-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loud", "0005_add_point_adjustment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="loudsubmission",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="loudsubmission",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
