"""empty message

Revision ID: 0823dcc4ef7a
Revises: b2b1a6077cca
Create Date: 2026-05-17 23:32:21.180551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0823dcc4ef7a'
down_revision: Union[str, Sequence[str], None] = 'b2b1a6077cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'is_deleted')
    # ### end Alembic commands ###
