# Generated by Django 5.2.8 on 2026-01-01 11:36

import django.db.models.deletion
import django.utils.timezone
import posts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x_link", models.URLField(max_length=500)),
                (
                    "redirect_token",
                    models.CharField(
                        db_index=True,
                        default=posts.models.generate_redirect_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("escrow", models.IntegerField(default=40)),
                ("initial_escrow", models.IntegerField(default=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                ("channel_id", models.BigIntegerField(blank=True, null=True)),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("credit_granted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "engagements",
            },
        ),
        migrations.CreateModel(
            name="SponsoredPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=100)),
                ("sponsor_contact", models.CharField(blank=True, max_length=200)),
                ("credit_reward", models.IntegerField(default=2)),
                ("total_budget", models.IntegerField()),
                ("remaining_budget", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorship",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "sponsored_posts",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created_at"], name="posts_status_ecf387_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "-created_at"], name="posts_user_id_dfa368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["redirect_token"], name="posts_redirec_eb86ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["user", "-created_at"], name="engagements_user_id_da592a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["post", "-created_at"], name="engagements_post_id_db9791_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post_engagement"
            ),
        ),
    ]
