# Generated by Django 5.2.8 on 2026-01-13 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("raffle", "Raffle"), ("score_based", "Score Based")],
                        max_length=20,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="engagement",
            name="like_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="engagement",
            name="reply_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="engagement",
            name="verification_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engagement",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="tweet_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="escrow",
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="post",
            name="initial_escrow",
            field=models.IntegerField(default=80),
        ),
        migrations.CreateModel(
            name="CampaignEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tweet_url", models.URLField(max_length=500)),
                ("tweet_id", models.CharField(blank=True, max_length=50)),
                ("verified", models.BooleanField(default=False)),
                ("verification_data", models.JSONField(blank=True, null=True)),
                (
                    "payout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payout_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="posts.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaign_entries",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "user"), name="unique_campaign_user_entry"
                    )
                ],
            },
        ),
    ]
