# Generated by Django 5.2.9 on 2026-01-16 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_v1_updates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_budget__gte", 0)),
                name="campaign_budget_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(("escrow__gte", 0)), name="post_escrow_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoredpost",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_budget__gte", 0)),
                name="sponsored_budget_non_negative",
            ),
        ),
    ]
