# Generated by Django 5.2.8 on 2026-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_add_check_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="campaign",
            name="entry_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for entries. Defaults to ends_at if not set.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="max_entries",
            field=models.IntegerField(
                blank=True,
                help_text="Max entries allowed (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="max_winners",
            field=models.IntegerField(
                default=1, help_text="Number of winners to select"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_engagements",
            field=models.IntegerField(
                default=0, help_text="Minimum total engagements required"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_posts",
            field=models.IntegerField(
                default=0, help_text="Minimum posts submitted required"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_sponsored_xp",
            field=models.IntegerField(
                default=0, help_text="Minimum XP required to enter (0 = open to all)"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_streak",
            field=models.IntegerField(
                default=0, help_text="Minimum current streak required"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_tweetscout_score",
            field=models.FloatField(
                default=0, help_text="Minimum TweetScout score required"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="prize_description",
            field=models.TextField(blank=True, help_text="Description of prize(s)"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="prize_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prize value in USD (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="require_x_linked",
            field=models.BooleanField(
                default=False, help_text="Require X/Twitter account linked"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="winner_selection_method",
            field=models.CharField(
                choices=[
                    ("random", "Random Draw"),
                    ("weighted_xp", "Weighted by XP"),
                    ("weighted_score", "Weighted by TweetScout"),
                    ("first_come", "First Come First Served"),
                ],
                default="random",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="winners_announced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="eligibility_snapshot",
            field=models.JSONField(
                default=dict, help_text="User stats captured at time of entry"
            ),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="entry_source",
            field=models.CharField(
                choices=[
                    ("miniapp", "Mini App"),
                    ("bot", "Telegram Bot"),
                    ("admin", "Admin Panel"),
                ],
                default="miniapp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="ineligibility_reason",
            field=models.TextField(
                blank=True, help_text="Why entry was marked ineligible"
            ),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="prize_claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="prize_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("eligible", "Eligible"),
                    ("ineligible", "Ineligible"),
                    ("winner", "Winner"),
                    ("claimed", "Prize Claimed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="tweet_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_sponsored_xp__gte", 0)),
                name="campaign_min_xp_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_winners__gte", 1)),
                name="campaign_max_winners_positive",
            ),
        ),
    ]
