# Generated by Django 5.2.8 on 2026-01-21 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_add_tweet_content_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engagement_ids",
                    models.JSONField(
                        default=list, help_text="List of engagement UUIDs in this batch"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "passed",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of verifications passed",
                        null=True,
                    ),
                ),
                (
                    "failed",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of verifications failed",
                        null=True,
                    ),
                ),
                (
                    "credits_awarded",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total karma awarded",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Result message for user"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="verificatio_user_id_c1a820_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="verificatio_status_2d0d96_idx",
                    ),
                ],
            },
        ),
    ]
