# Generated by Django 5.2.8 on 2026-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_remove_discord_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="credit_granted",
            field=models.BooleanField(default=False),
        ),
    ]
