# Generated by Django 5.2.8 on 2026-01-30 18:11

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_alter_engagement_credit_granted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
