# Generated by Django 5.2.8 on 2026-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_claimed_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
