# Generated by Django 5.2.8 on 2026-01-13 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_assist_count_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="intent_reply_count_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="intent_usage_reset_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pro_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
