# Generated by Django 5.2.8 on 2026-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_v1_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kaito_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kaito_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kaito_yaps_30d",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="kaito_yaps_lifetime",
            field=models.FloatField(default=0),
        ),
    ]
