# Generated by Django 5.2.9 on 2026-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0007_sitesetting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Engagement Audit",
                "verbose_name_plural": "Engagement Audits",
            },
        ),
        migrations.RenameIndex(
            model_name="xprofile",
            new_name="x_profiles_usernam_eea3e4_idx",
            old_name="x_profiles_usernam_c5f5e2_idx",
        ),
        migrations.RenameIndex(
            model_name="xprofile",
            new_name="x_profiles_x_user__5a4776_idx",
            old_name="x_profiles_x_user__e5e1f3_idx",
        ),
        migrations.RenameIndex(
            model_name="xprofile",
            new_name="x_profiles_score_fa7841_idx",
            old_name="x_profiles_score_a1b2c3_idx",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("credits__gte", 0)),
                name="user_credits_non_negative",
            ),
        ),
    ]
