# Generated by Django 5.2.8 on 2026-01-17 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0009_add_honesty_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned from sponsored engagement"),
                            ("admin_grant", "Admin grant"),
                            ("admin_revoke", "Admin revoke"),
                            ("bonus", "Bonus XP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "xp_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="sponsored_engagements",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="sponsored_xp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_sponsored_xp_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("sponsored_xp__gte", 0)),
                name="user_sponsored_xp_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="xptransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xp_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="xptransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="xp_transact_user_id_616108_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xptransaction",
            index=models.Index(fields=["type"], name="xp_transact_type_39f8c1_idx"),
        ),
    ]
