# Generated by Django 5.2.8 on 2026-01-20 14:26
# Modified: Use IF EXISTS for fields already removed in 0023

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_kaito_fields"),
    ]

    operations = [
        # These fields were already removed in 0023 using raw SQL.
        # Use RunSQL with IF EXISTS to make this migration idempotent.
        migrations.RunSQL(
            sql="""
                ALTER TABLE users DROP COLUMN IF EXISTS kaito_last_updated;
                ALTER TABLE users DROP COLUMN IF EXISTS kaito_linked_at;
                ALTER TABLE users DROP COLUMN IF EXISTS kaito_yaps_30d;
                ALTER TABLE users DROP COLUMN IF EXISTS kaito_yaps_lifetime;
                ALTER TABLE x_profiles DROP COLUMN IF EXISTS kaito_yaps_lifetime;
                ALTER TABLE x_profiles DROP COLUMN IF EXISTS raw_kaito_data;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("decimal", "Decimal"),
                    ("bool", "Boolean"),
                    ("str", "String"),
                ],
                default="int",
                max_length=10,
            ),
        ),
    ]
