# Generated by Django 5.2.8 on 2026-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_kaito_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kaito_last_updated",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_linked_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_yaps_30d",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_yaps_lifetime",
        ),
        migrations.RemoveField(
            model_name="xprofile",
            name="kaito_yaps_lifetime",
        ),
        migrations.RemoveField(
            model_name="xprofile",
            name="raw_kaito_data",
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("decimal", "Decimal"),
                    ("bool", "Boolean"),
                    ("str", "String"),
                ],
                default="int",
                max_length=10,
            ),
        ),
    ]
