# Generated by Django 5.2.8 on 2026-01-23 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def whitelist_existing_users_and_fix_x_username(apps, schema_editor):
    """
    Data migration:
    1. Convert empty x_username to NULL (required for unique constraint)
    2. Set is_whitelisted=True for all existing users
    """
    User = apps.get_model('core', 'User')

    # Fix empty strings → NULL for unique constraint
    User.objects.filter(x_username='').update(x_username=None)

    # Whitelist all existing users
    User.objects.all().update(is_whitelisted=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_email_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_whitelisted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        # First allow NULL in x_username (without unique yet)
        migrations.AlterField(
            model_name="user",
            name="x_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Data migration to fix empty strings → NULL and whitelist users
        migrations.RunPython(
            whitelist_existing_users_and_fix_x_username,
            reverse_code=migrations.RunPython.noop
        ),
        # Skip unique constraint - there are duplicate x_usernames in production
        # migrations.AlterField(
        #     model_name="user",
        #     name="x_username",
        #     field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        # ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "join_token",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("telegram_username", models.CharField(blank=True, max_length=50)),
                ("telegram_display_name", models.CharField(blank=True, max_length=100)),
                (
                    "x_username",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (email only)"),
                            ("submitted", "Submitted (waiting approval)"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "db_table": "waitlist_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
