# Generated by Django 5.2.9 on 2026-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_waitlist_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="x_username",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
