# Generated by Django 5.2.8 on 2026-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_discord_support"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_idempot_d892f2_idx",
            old_name="transaction_idempotency_idx",
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="email_already_registered_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When 'already registered' email was last sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="email_confirmation_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When confirmation email was successfully sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="email_last_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Last email error message for debugging",
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="email_send_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of email send attempts"
            ),
        ),
    ]
