# Generated by Django 5.2.8 on 2026-01-27 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_waitlist_x_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature", models.CharField(db_index=True, max_length=50)),
                ("interests", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Interest",
                "verbose_name_plural": "Feature Interests",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
