# Generated by Django 5.2.8 on 2026-01-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_feature_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loud_access",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Enable LOUD feature for this user",
            ),
        ),
    ]
