# Generated by Django 5.2.8 on 2026-01-30 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add FSM-related fields to WaitlistEntry for state machine support."""

    dependencies = [
        ("core", "0033_add_loud_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
