# Generated by Django 5.2.8 on 2026-01-30 18:11
# Modified: Removed kaito field removals (already done in earlier migrations)

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    """Convert WaitlistEntry status to FSMField for state machine support."""

    dependencies = [
        ("core", "0034_add_fsm_waitlist_fields"),
    ]

    operations = [
        # Note: Kaito field removals were already done in migrations 0023/0024
        # This migration only alters the status field to use FSMField
        migrations.AlterField(
            model_name="waitlistentry",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending (email only)"),
                    ("submitted", "Submitted (waiting approval)"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
