# Generated by Django 5.2.8 on 2026-01-30 18:16
# Modified: Removed kaito field removals (already done in earlier migrations)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add OutboxEvent model for reliable notifications."""

    dependencies = [
        ("core", "0035_remove_user_kaito_last_updated_and_more"),
    ]

    operations = [
        # Note: Kaito field removals were already done in earlier migrations
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("telegram_notify", "Telegram Notification"),
                            ("email_notify", "Email Notification"),
                            ("waitlist_approved", "Waitlist Approval"),
                            ("credits_earned", "Credits Earned"),
                            ("post_completed", "Post Completed"),
                            ("campaign_winner", "Campaign Winner"),
                            ("external_api", "External API Call"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Event-specific data"),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="outbox_even_status_8ec420_idx",
                    ),
                    models.Index(
                        fields=["event_type", "status"],
                        name="outbox_even_event_t_707000_idx",
                    ),
                ],
            },
        ),
    ]
