# Generated by Django 5.2.8 on 2026-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_accounting_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kaito_last_updated",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_linked_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_yaps_30d",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kaito_yaps_lifetime",
        ),
        migrations.RemoveField(
            model_name="xprofile",
            name="kaito_yaps_lifetime",
        ),
        migrations.RemoveField(
            model_name="xprofile",
            name="raw_kaito_data",
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("telegram_notify", "Telegram Notification"),
                    ("email_notify", "Email Notification"),
                    ("waitlist_approved", "Waitlist Approval"),
                    ("waitlist_submitted", "Waitlist Submission"),
                    ("credits_earned", "Credits Earned"),
                    ("post_completed", "Post Completed"),
                    ("campaign_winner", "Campaign Winner"),
                    ("external_api", "External API Call"),
                ],
                max_length=50,
            ),
        ),
    ]
