# Generated by Django 5.2.8 on 2026-02-01 08:04

import secrets
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generate_referral_codes(apps, schema_editor):
    """Generate unique referral codes for all existing users."""
    User = apps.get_model('core', 'User')
    existing_codes = set()

    for user in User.objects.filter(referral_code=''):
        for _ in range(10):  # Max 10 attempts
            code = secrets.token_urlsafe(6)[:8].upper()
            if code not in existing_codes and not User.objects.filter(referral_code=code).exists():
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                existing_codes.add(code)
                break


def reverse_referral_codes(apps, schema_editor):
    """Reverse: clear all referral codes."""
    User = apps.get_model('core', 'User')
    User.objects.all().update(referral_code='')


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0039_add_waitlist_submitted_event_type"),
    ]

    operations = [
        # Step 1: Add referral_code field WITHOUT unique constraint first.
        # db_index is deliberately omitted here — it would create a _like
        # suffix index with the same name Django wants for the unique index
        # added in Step 3, causing "relation already exists" on fresh DBs.
        # The unique=True in Step 3 creates the needed index anyway.
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique referral code for this user",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who referred this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_referrals",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of approved referrals"
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="referral_code_used",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Referral code used during signup",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                help_text="User who referred this waitlist entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("telegram_notify", "Telegram Notification"),
                    ("email_notify", "Email Notification"),
                    ("email_waitlist_confirmation", "Waitlist Confirmation Email"),
                    ("email_already_registered", "Already Registered Email"),
                    ("waitlist_approved", "Waitlist Approval"),
                    ("waitlist_submitted", "Waitlist Submission"),
                    ("credits_earned", "Credits Earned"),
                    ("post_completed", "Post Completed"),
                    ("campaign_winner", "Campaign Winner"),
                    ("tweetscout_fetch", "TweetScout Fetch"),
                    ("external_api", "External API Call"),
                ],
                max_length=50,
            ),
        ),
        # Step 2: Generate referral codes for existing users
        migrations.RunPython(generate_referral_codes, reverse_referral_codes),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique referral code for this user",
                max_length=16,
                unique=True,
            ),
        ),
        # Step 4: Add check constraints
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("referred_by", models.F("id")), _negated=True),
                name="user_no_self_referral",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_referrals__gte", 0)),
                name="user_total_referrals_non_negative",
            ),
        ),
    ]
