# Generated by Django 5.2.11 on 2026-02-14 08:44

import django_fsm
from django.db import migrations, models


def convert_pending_to_submitted(apps, schema_editor):
    """Convert any existing PENDING waitlist entries to SUBMITTED."""
    WaitlistEntry = apps.get_model('core', 'WaitlistEntry')
    updated = WaitlistEntry.objects.filter(status='pending').update(status='submitted')
    if updated:
        print(f"  Converted {updated} PENDING waitlist entries to SUBMITTED")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_referral_fields'),
    ]

    operations = [
        # Data migration: convert PENDING -> SUBMITTED before removing the choice
        migrations.RunPython(
            convert_pending_to_submitted,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_already_registered_sent_at',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_confirmation_sent_at',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_last_error',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_send_attempts',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='join_token',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='x_avatar_url',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='x_display_name',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='x_fetched_at',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='x_followers_count',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='x_is_verified',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='x_link',
            field=models.URLField(blank=True, default='', help_text='Original X profile URL submitted by user', max_length=500),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('telegram_notify', 'Telegram Notification'), ('email_notify', 'Email Notification'), ('waitlist_approved', 'Waitlist Approval'), ('waitlist_submitted', 'Waitlist Submission'), ('credits_earned', 'Credits Earned'), ('post_completed', 'Post Completed'), ('campaign_winner', 'Campaign Winner'), ('tweetscout_fetch', 'TweetScout Fetch'), ('external_api', 'External API Call')], max_length=50),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=django_fsm.FSMField(choices=[('submitted', 'Submitted (waiting approval)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
