# Generated by Django 5.2.11 on 2026-02-14 09:49

import secrets

from django.db import migrations, models


def generate_referral_codes(apps, schema_editor):
    """Generate unique referral codes for existing waitlist entries."""
    WaitlistEntry = apps.get_model('core', 'WaitlistEntry')
    User = apps.get_model('core', 'User')

    existing_codes = set(
        User.objects.filter(referral_code__isnull=False)
        .exclude(referral_code='')
        .values_list('referral_code', flat=True)
    )

    for entry in WaitlistEntry.objects.filter(referral_code=''):
        for _ in range(10):
            code = secrets.token_urlsafe(6)[:8].upper()
            if code not in existing_codes:
                existing_codes.add(code)
                entry.referral_code = code
                entry.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_simplify_waitlist_remove_dead_fields'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='waitlistentry',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Unique referral code for sharing', max_length=16),
        ),
        # Step 2: Backfill codes for existing entries
        migrations.RunPython(generate_referral_codes, migrations.RunPython.noop),
        # Step 3: Add unique + index constraints
        migrations.AlterField(
            model_name='waitlistentry',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique referral code for sharing', max_length=16, unique=True),
        ),
    ]
