# Generated by Django 5.2.11 on 2026-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_waitlist_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('telegram_notify', 'Telegram Notification'), ('waitlist_approved', 'Waitlist Approval'), ('waitlist_submitted', 'Waitlist Submission'), ('credits_earned', 'Credits Earned'), ('post_completed', 'Post Completed'), ('campaign_winner', 'Campaign Winner'), ('tweetscout_fetch', 'TweetScout Fetch'), ('external_api', 'External API Call')], max_length=50),
        ),
    ]
