# Generated by Django 5.2.11 on 2026-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_email_notify_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='niche',
            field=models.CharField(blank=True, choices=[('memecoins', 'Memecoins'), ('gamefi', 'GameFi'), ('trading', 'Trading'), ('nfts', 'NFTs'), ('defi', 'DeFi'), ('ai_tech', 'AI / Tech'), ('daos', 'DAOs')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='other_platforms',
            field=models.JSONField(blank=True, default=list, help_text="Other platforms: [{platform: 'youtube'|'tiktok'|'other', username: '...', platform_name?: '...'}]"),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='region',
            field=models.CharField(blank=True, choices=[('north_america', 'North America'), ('europe', 'Europe'), ('middle_east', 'Middle East'), ('south_asia', 'South Asia'), ('southeast_asia', 'Southeast Asia'), ('east_asia', 'East Asia'), ('africa', 'Africa'), ('latin_america', 'Latin America'), ('oceania', 'Oceania'), ('cis_eastern_europe', 'CIS / Eastern Europe')], default='', max_length=30),
        ),
    ]
