# Generated by Django 5.2.11 on 2026-04-20 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_install_django_q_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_claimed_x_user_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_claimed_x_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='x_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='x_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='x_verified_previously',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='XVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_x_username', models.CharField(help_text='x_username the user originally submitted on the waitlist', max_length=50)),
                ('claimed_x_username', models.CharField(help_text='Username returned by X OAuth (the one user is trying to verify with)', max_length=50)),
                ('claimed_x_user_id', models.CharField(help_text='Numeric X user ID from OAuth — the source of truth', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Admin reviewer notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'x_verification_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='x_verificat_status_b84439_idx'), models.Index(fields=['user', 'status'], name='x_verificat_user_id_b3e58c_idx')],
            },
        ),
    ]
